USE personal;
-- a
SELECT NOMBRE, APELLIDOS FROM EMPLEADOS;

-- b
SELECT DISTINCT APELLIDOS FROM EMPLEADOS;

-- c
SELECT * FROM EMPLEADOS WHERE APELLIDOS = 'López';

-- d
SELECT * FROM EMPLEADOS WHERE APELLIDOS IN ('López', 'Pérez');

-- e
SELECT NOMBRE, CLAVE_EMPLEADO FROM EMPLEADOS WHERE CLAVE_DEPTO = 4;

-- f
SELECT * FROM EMPLEADOS WHERE CLAVE_DEPTO IN (1, 3) ORDER BY NOMBRE;

-- g
SELECT NOMBRE, APELLIDOS FROM EMPLEADOS WHERE APELLIDOS LIKE 'H%';

-- h
SELECT * FROM DEPARTAMENTOS WHERE PRESUPUESTO BETWEEN 50000 AND 70000;

-- i
SELECT CLAVE_EMPLEADO, NOMBRE, APELLIDOS 
FROM EMPLEADOS 
WHERE CLAVE_DEPTO = (SELECT CLAVE_DEPTO FROM DEPARTAMENTOS WHERE NOMBRE = 'Contabilidad');

-- j
SELECT E.NOMBRE, E.APELLIDOS, D.NOMBRE AS NOMBRE_DEPARTAMENTO
FROM EMPLEADOS E
JOIN DEPARTAMENTOS D ON E.CLAVE_DEPTO = D.CLAVE_DEPTO;
