-- a
CREATE VIEW Personal AS
SELECT * FROM EMPLEADOS 
WHERE CLAVE_DEPTO = (SELECT CLAVE_DEPTO FROM DEPARTAMENTOS WHERE NOMBRE = 'Personal');

-- b
CREATE VIEW Perez AS
SELECT * FROM EMPLEADOS 
WHERE APELLIDOS = 'Pérez';

-- c
CREATE VIEW Grandes_presupuestos AS
SELECT * FROM DEPARTAMENTOS 
WHERE PRESUPUESTO >= 50000;
